// First-party site starters: presentation + content model + sample content.
// Templates consume brand tokens, so the same functionality works with every look.
const field = (name, label, widget = "string", extra = {}) => ({ name, label, widget, required: false, ...extra });
export const looks = [
  { id: "editorial", label: "Editorial", description: "Warm paper, confident type, terracotta details.", brand: { scheme: "light", radius: "2px", motion: "off", fonts: { heading: "jost", body: "jost" }, colors: { bg: "#f5f3eb", surface: "#e9e7db", ink: "#252621", muted: "#64675c", accent: "#b53b20", border: "#d9d9cd" } } },
  { id: "gallery", label: "Gallery", description: "Bright canvas, restrained green, room for images.", brand: { scheme: "light", radius: "8px", motion: "off", fonts: { heading: "inter", body: "inter" }, colors: { bg: "#ffffff", surface: "#f0f3f0", ink: "#172a24", muted: "#52655c", accent: "#28694d", border: "#d5dfd9" } } },
  { id: "nocturne", label: "Nocturne", description: "Dark surfaces, warm text and a soft lime accent.", brand: { scheme: "dark", radius: "4px", motion: "off", fonts: { heading: "space-grotesk", body: "inter" }, colors: { bg: "#20231e", surface: "#2c3028", ink: "#f4f3e8", muted: "#b7c0ad", accent: "#d3e5a9", border: "#4d5544" } } },
  { id: "folio", label: "Folio", description: "Bookish serif headings, ivory paper and deep burgundy.", brand: { scheme: "light", radius: "2px", motion: "off", fonts: { heading: "fraunces", body: "system-serif" }, colors: { bg: "#fbf6ed", surface: "#eee5d8", ink: "#302822", muted: "#706053", accent: "#843649", border: "#d9cbbb" } } },
  { id: "cobalt", label: "Cobalt", description: "Crisp typography, cool white and electric blue.", brand: { scheme: "light", radius: "10px", motion: "off", fonts: { heading: "space-grotesk", body: "inter" }, colors: { bg: "#f7f9ff", surface: "#e9eefb", ink: "#15213d", muted: "#56627a", accent: "#234fc4", border: "#cbd5eb" } } },
];
const css = `<style>
.starter,.starter * { box-sizing:border-box; }
.starter { overflow-wrap:anywhere; max-width:76rem; margin:auto; padding:clamp(2rem,5vw,5rem) 1.5rem; color:var(--ink); background:var(--bg); font-family:var(--font-prose); }
.starter a { color:var(--accent); text-underline-offset:.22em; }
.starter a:focus-visible { outline:3px solid var(--accent); outline-offset:4px; }
.starter .st-kicker { font:.7rem var(--font-mono,ui-monospace,monospace); letter-spacing:.13em; text-transform:uppercase; color:var(--accent); }
.starter h1 { font-family:var(--font-heading); font-size:clamp(2.7rem,6vw,5.5rem); font-weight:500; letter-spacing:-.045em; line-height:1.04; margin:1.2rem 0; max-width:16ch; }
.starter .st-lead { font-size:1.2rem; line-height:1.75; color:var(--muted); max-width:40rem; white-space:pre-line; }
.starter .st-actions { display:flex; flex-wrap:wrap; gap:1rem; margin:2rem 0; }
.starter .st-button { display:inline-block; padding:.8rem 1.2rem; background:var(--ink); color:var(--bg); border-radius:var(--radius); text-decoration:none; }
.starter .st-hero > * { min-width:0; }
.starter .st-hero { display:grid; grid-template-columns:1.25fr 1fr; gap:4rem; align-items:center; padding-bottom:3rem; }
.starter .st-cover { aspect-ratio:4/3; overflow:hidden; background:var(--surface); border:1px solid var(--border); border-radius:var(--radius); display:grid; place-items:center; position:relative; }
.starter .st-cover img { width:100%; height:100%; object-fit:cover; position:absolute; inset:0; }
.starter .st-cover > span { padding:1rem; font-family:var(--font-mono,ui-monospace,monospace); font-size:.8rem; color:var(--muted); text-align:center; }
.starter .st-grid { display:grid; grid-template-columns:repeat(3,minmax(0,1fr)); gap:1.5rem; margin:2.5rem 0; }
.starter .st-card { border:1px solid var(--border); border-radius:var(--radius); padding:1.5rem; }
.starter .st-card h2,.starter .st-card h3 { font-family:var(--font-heading); font-size:1.5rem; line-height:1.2; font-weight:500; margin:1.2rem 0 .6rem; }
.starter .st-card p { line-height:1.7; color:var(--muted); }
.starter .st-meta { display:flex; flex-wrap:wrap; gap:.6rem 1.2rem; color:var(--muted); font-size:.9rem; }
.starter .st-status { display:inline-block; background:var(--surface); padding:.3rem .65rem; border-radius:var(--radius); margin:.75rem 0; font-size:.8rem; }
.starter .st-body { max-width:46rem; font-size:1.15rem; line-height:1.8; margin:3rem auto; }
.starter .st-body img { max-width:100%; height:auto; }
.starter .st-facts { display:grid; grid-template-columns:repeat(3,1fr); gap:1rem; padding:1.5rem 0; border-block:1px solid var(--border); }
.starter .st-facts dt { font-size:.75rem; color:var(--muted); } .starter .st-facts dd { font-size:1.2rem; margin:.4rem 0; }
.starter .st-gallery { display:grid; grid-template-columns:repeat(2,minmax(0,1fr)); gap:1rem; margin-top:2rem; }
.starter .st-gallery figure { margin:0; } .starter .st-gallery img { width:100%; aspect-ratio:4/3; object-fit:cover; border-radius:var(--radius); } .starter .st-gallery figcaption { font-size:.8rem; color:var(--muted); margin:.5rem 0; }
.starter .st-end { margin-top:4rem; padding-top:2rem; border-top:1px solid var(--border); }
.starter .st-demo { padding:.65rem 1rem; border:1px dashed var(--border); color:var(--muted); font-size:.8rem; margin-bottom:1rem; }
@media(max-width:800px) { .starter .st-hero { grid-template-columns:1fr; gap:1.5rem; } .starter .st-grid { grid-template-columns:repeat(2,minmax(0,1fr)); } }
@media(max-width:520px) { .starter .st-grid,.starter .st-gallery { grid-template-columns:1fr; } .starter .st-facts { grid-template-columns:repeat(2,1fr); } }
</style>`;
const homeFields = [field("eyebrow", "Introduction label", "string", {group:"Introduction"}), field("heading", "Headline", "string", {required:true,group:"Introduction"}), field("intro", "Introduction", "text", {group:"Introduction"}), field("featuredImage", "Cover image", "image", {group:"Introduction"}), field("imageAlt", "Image description", "string", {group:"Introduction"}), field("imagePlaceholder", "Image placeholder", "string", {group:"Introduction"}), field("browseLabel", "Browse button", "string", {group:"Links"}), field("browseUrl", "Browse URL", "string", {group:"Links"}), field("contactLabel", "Contact link text", "string", {group:"Contact"}), field("contactUrl", "Contact link", "string", {group:"Contact",hint:"Your mailto: email link or contact page URL. Leave blank to hide."}),field("aboutTitle", "About heading", "string", {group:"About"}),field("aboutText", "About text", "text", {group:"About"}),field("services", "Areas of work", "list", {group:"Areas of work",fields:[field("title","Title"),field("description","Description","text")]}),field("demoNote", "Starter note", "text", {group:"Getting ready",hint:"Replace the sample content, then clear this note before publishing."})];
const homeHtml = `${css}<section class="starter">{{#if demoNote}}<p class="st-demo">{{ demoNote }}</p>{{/if}}<div class="st-hero"><div><p class="st-kicker">{{ eyebrow }}</p><h1>{{ heading }}</h1><p class="st-lead">{{ intro }}</p><div class="st-actions"><a class="st-button" href="{{ browseUrl }}">{{ browseLabel }} ↗</a>{{#if contactUrl}}<a href="{{ contactUrl }}">{{ contactLabel }}</a>{{/if}}</div></div><div class="st-cover"><span>{{ imagePlaceholder }}</span>{{#if featuredImage}}<img src="{{ featuredImage }}" alt="{{ imageAlt }}" />{{/if}}</div></div><div class="st-grid st-services">{{#each services}}<article class="st-card"><h2>{{ title }}</h2><p>{{ description }}</p></article>{{/each}}</div><section class="st-end"><h2>{{ aboutTitle }}</h2><p class="st-lead">{{ aboutText }}</p></section></section>`;
const galleryField = field("gallery", "Image gallery", "list", { fields: [field("image", "Image", "image"),field("alt", "Image description"),field("caption", "Caption")] });
const galleryHtml = `{{#if gallery}}<div class="st-gallery">{{#each gallery}}{{#if image}}<figure><img src="{{ image }}" alt="{{ alt }}" loading="lazy" />{{#if caption}}<figcaption>{{ caption }}</figcaption>{{/if}}</figure>{{/if}}{{/each}}</div>{{/if}}`;
function starter({id,label,description,collection,singular,listingHeading,base,features,notIncluded,fields,itemFields,detailContent,cardContent,home,samples,layoutCss=""}) {
 const detail = `${id}-detail`, listing=`${id}-index`, landing=`${id}-home`;
 const design = `<style>${layoutCss}</style>`;
 const allFields=[field("title","Title","string",{required:true}),field("summary","Summary","text"),field("featuredImage","Featured image","image"),field("imageAlt","Image description"),...fields,field("backLabel","Back link text","string",{default:`Back to ${collection}`}),galleryField,field("contactLabel","Contact link text"),field("contactUrl","Contact link","string",{hint:"mailto: address or a contact-page URL. No form service is connected."}),field("demoNote","Example-content note","text"),field("draft","Draft","boolean",{default:true})];
 return { id,label,description,version:"1.1.0",features,notIncluded,looks,
  contentType:{name:collection,label:collection[0].toUpperCase()+collection.slice(1),labelSingular:singular ?? (collection==='projects'?'Project':'Property'),folder:`content/${collection}`,localized:true,body:"rich",thumbnail:"featuredImage",fieldsFrom:detail,route:{base,template:detail,list:{template:listing,sortBy:"title",order:"asc",slots:{heading:listingHeading ?? (collection==='projects'?'Selected work':'Property collection'),intro:'Example content. Replace these entries with your own before publishing.',emptyText:'New entries will appear here when they are marked Ready.'}}}},
  home:{stem:id === "events" ? "gatherings" : id,preset:landing,title:label,slots:home},samples:samples.map(sample=>({...sample,data:{backLabel:`Back to ${collection}`,...sample.data}})),
  templates:{
   [landing]:{position:"page",fields:{name:landing,label:`${label} introduction`,body:false,fields:homeFields},html:homeHtml.replace('class="starter"',`class="starter" data-design="${id}"`)+design},
   [detail]:{position:"detail",fields:{name:detail,label:`${label} detail`,body:true,fields:allFields},html:`${css}<article class="starter" data-design="${id}"><a href="{{ indexUrl }}">← {{ backLabel }}</a>{{#if demoNote}}<p class="st-demo">{{ demoNote }}</p>{{/if}}${detailContent}<div class="st-body">{{{ body }}}</div>${galleryHtml}{{#if contactUrl}}<div class="st-end"><a class="st-button" href="{{ contactUrl }}">{{ contactLabel }} ↗</a></div>{{/if}}</article>${design}`},
   [listing]:{position:"list",fields:{name:listing,label:`${label} listing`,body:false,listing:{of:collection,item:["title","summary","featuredImage","imageAlt",...itemFields]},fields:[field("heading","Heading","string",{required:true}),field("intro","Introduction","text"),field("emptyText","Empty state")]},html:`${css}<section class="starter" data-design="${id}"><h1>{{ heading }}</h1><p class="st-lead">{{ intro }}</p><div class="st-grid">{{#each entries}}<article class="st-card"><a href="{{ url }}"><div class="st-cover"><span>{{ title }}</span>{{#if featuredImage}}<img src="{{ featuredImage }}" alt="{{ imageAlt }}" loading="lazy" />{{/if}}</div><h2>{{ title }}</h2></a><p>{{ summary }}</p>${cardContent}</article>{{/each}}</div>{{#if isEmpty}}<p class="st-lead">{{ emptyText }}</p>{{/if}}</section>${design}`},
  },
 };
}
export const STARTERS = [
 starter({layoutCss:`
.starter[data-design="portfolio"] .st-hero { grid-template-columns:1.4fr 1fr; align-items:end; gap:3rem; }
.starter[data-design="portfolio"] .st-hero .st-cover { aspect-ratio:3/4; border-radius:45% 45% 0 0; background:linear-gradient(145deg,var(--surface),var(--bg)); }
.starter[data-design="portfolio"] .st-services { counter-reset:service; border-top:1px solid var(--border); }
.starter[data-design="portfolio"] .st-services .st-card { counter-increment:service; border:0; padding:2rem 0; }
.starter[data-design="portfolio"] .st-services .st-card:before { content:"0" counter(service); font-family:var(--font-mono,ui-monospace,monospace); color:var(--accent); }
@media(max-width:800px) { .starter[data-design="portfolio"] .st-hero { grid-template-columns:1fr; } .starter[data-design="portfolio"] .st-hero .st-cover { aspect-ratio:4/3; border-radius:var(--radius); } }
`,id:"portfolio",label:"Portfolio",description:"An editorial home for independent creatives, studios and their work.",collection:"projects",base:"projects",features:["Editable introduction page","Project index and case studies","Project categories, client and year","Image galleries","Email or contact-page links","Five brand styles"],notIncluded:["File delivery or client accounts","Payments","Contact-form processing"],
 fields:[field("category","Discipline"),field("client","Client"),field("year","Year")],itemFields:["category","year"],
 detailContent:`<p class="st-kicker">{{ category }}</p><h1>{{ title }}</h1><p class="st-lead">{{ summary }}</p><div class="st-meta">{{#if client}}<span>{{ client }}</span>{{/if}}{{#if year}}<span>{{ year }}</span>{{/if}}</div>{{#if featuredImage}}<div class="st-cover"><img src="{{ featuredImage }}" alt="{{ imageAlt }}" /></div>{{/if}}`,cardContent:`<div class="st-meta"><span>{{ category }}</span><span>{{ year }}</span></div>`,
 home:{eyebrow:"Independent practice",heading:"Good work, thoughtfully made.",intro:"Introduce your practice, your point of view and the people you help. This space is yours to make specific.",imagePlaceholder:"Add a project image",browseLabel:"Explore the work",browseUrl:"/projects/",contactLabel:"Start a conversation",contactUrl:"",aboutTitle:"A practice with a point of view.",aboutText:"Replace this with a short introduction to your work and how you collaborate.",services:[{title:"Identity",description:"Describe the first area of your practice."},{title:"Digital",description:"Describe the second area of your practice."},{title:"Collaboration",description:"Explain how you work with clients and collaborators."}],demoNote:"Starter content. Add your words, images and contact details before publishing."},
 samples:[{stem:"example-identity",data:{title:"Example: a visual identity",summary:"Replace this example with the context and outcome of a real project.",category:"Brand identity",client:"Example client",year:"2026"},body:"<h2>The brief</h2><p>Describe the problem you helped solve.</p><h2>The work</h2><p>Tell the story behind your decisions and the result.</p>"},{stem:"example-digital",data:{title:"Example: a digital experience",summary:"A second case study, ready for your own story and images.",category:"Digital design",year:"2026"},body:"<p>Use this space for the story of your project.</p>"}]}),
 starter({layoutCss:`
.starter[data-design="real-estate"] .st-hero { grid-template-columns:1fr; gap:2rem; }
.starter[data-design="real-estate"] .st-hero > div:first-child { display:grid; grid-template-columns:1.2fr 1fr; gap:0 3rem; align-items:start; }
.starter[data-design="real-estate"] .st-hero h1 { grid-column:1; grid-row:2 / 4; margin-top:0; }
.starter[data-design="real-estate"] .st-hero .st-kicker { grid-column:1 / -1; }
.starter[data-design="real-estate"] .st-hero .st-cover { aspect-ratio:21/9; background:linear-gradient(120deg,var(--surface),var(--bg)); }
.starter[data-design="real-estate"] .st-card { padding:1rem; background:var(--surface); }
@media(max-width:800px) { .starter[data-design="real-estate"] .st-hero > div:first-child { display:block; } .starter[data-design="real-estate"] .st-hero .st-cover { aspect-ratio:4/3; } }
`,id:"real-estate",label:"Real estate",description:"A considered property showcase with structured listings and useful detail pages.",collection:"properties",base:"properties",features:["Editable agency introduction","Property index and detail pages","Price, location and property facts","Availability status","Property galleries","Email or contact-page links","Five brand styles"],notIncluded:["MLS / IDX property feeds","Map or geocoding services","Booking and inquiry-form processing","Search and filter controls"],
 fields:[field("price","Price display","string",{hint:"Include the currency and any period, for example €1,500 / month."}),field("location","Location"),field("status","Availability","select",{options:["Available","Under offer","Sold","Let"]}),field("bedrooms","Bedrooms","number",{valueType:"int"}),field("bathrooms","Bathrooms","number"),field("area","Area, including units"),field("bedroomsLabel","Bedrooms label","string",{default:"Bedrooms"}),field("bathroomsLabel","Bathrooms label","string",{default:"Bathrooms"}),field("areaLabel","Area label","string",{default:"Area"})],itemFields:["price","location","status","bedrooms","bathrooms","area","bedroomsLabel","bathroomsLabel"],
 detailContent:`<p class="st-kicker">{{ location }}</p><h1>{{ title }}</h1><p class="st-lead">{{ summary }}</p><div class="st-meta"><strong>{{ price }}</strong>{{#if status}}<span class="st-status">{{ status }}</span>{{/if}}</div>{{#if featuredImage}}<div class="st-cover"><img src="{{ featuredImage }}" alt="{{ imageAlt }}" /></div>{{/if}}<dl class="st-facts"><div><dt>{{ bedroomsLabel }}</dt><dd>{{ bedrooms }}</dd></div><div><dt>{{ bathroomsLabel }}</dt><dd>{{ bathrooms }}</dd></div><div><dt>{{ areaLabel }}</dt><dd>{{ area }}</dd></div></dl>`,cardContent:`<p>{{ location }}</p><strong>{{ price }}</strong>{{#if status}}<span class="st-status">{{ status }}</span>{{/if}}<div class="st-meta"><span>{{ bedrooms }} {{ bedroomsLabel }}</span><span>{{ bathrooms }} {{ bathroomsLabel }}</span><span>{{ area }}</span></div>`,
 home:{eyebrow:"A local perspective",heading:"Find your next place in the world.",intro:"Introduce your agency and the places you know best. Give people a reason to trust your local knowledge.",imagePlaceholder:"Add a property or neighborhood image",browseLabel:"Explore properties",browseUrl:"/properties/",contactLabel:"Talk to us",contactUrl:"",aboutTitle:"Good advice starts with listening.",aboutText:"Explain how you help buyers, sellers or renters. Add your own qualifications and service area.",services:[{title:"Buy",description:"Describe how you help people find a home."},{title:"Sell",description:"Explain your approach to presenting a property."},{title:"Local knowledge",description:"Introduce the areas you work in."}],demoNote:"Starter content. Replace the example properties, text and contact details before publishing."},
 samples:[{stem:"example-courtyard-home",data:{title:"Example: courtyard home",summary:"Fictional property for demonstrating the layout. Replace with a real, authorized listing.",price:"Example price",location:"Example neighborhood",status:"Available",bedrooms:3,bathrooms:2,area:"Example area",bedroomsLabel:"Bedrooms",bathroomsLabel:"Bathrooms",areaLabel:"Area"},body:"<h2>About this property</h2><p>This is sample content, not a real listing. Add an accurate description, photographs and contact details for your own property.</p>"},{stem:"example-city-apartment",data:{title:"Example: city apartment",summary:"A fictional second listing to show the property collection.",price:"Example price",location:"Example district",status:"Under offer",bedrooms:2,bathrooms:1,area:"Example area",bedroomsLabel:"Bedrooms",bathroomsLabel:"Bathrooms",areaLabel:"Area"},body:"<p>Replace this sample with your own authorized property information.</p>"}]}),
];
STARTERS.push(
 starter({id:"writer",label:"Writer",description:"A personal publication with a generous reading column and a quietly ordered essay archive.",collection:"essays",singular:"Essay",listingHeading:"Essays & observations",base:"essays",features:["Editable author introduction","Essay archive and reading pages","Topics and bylines","Image galleries","Five brand styles"],notIncluded:["Email newsletter delivery","Paid subscriptions","Reader accounts"],
 fields:[field("topic","Topic"),field("byline","Byline")],itemFields:["topic","byline"],
 detailContent:`<p class="st-kicker">{{ topic }}</p><h1>{{ title }}</h1><p class="st-lead">{{ summary }}</p>{{#if byline}}<p class="st-meta">{{ byline }}</p>{{/if}}{{#if featuredImage}}<div class="st-cover"><img src="{{ featuredImage }}" alt="{{ imageAlt }}" /></div>{{/if}}`,cardContent:`<div class="st-meta"><span>{{ topic }}</span><span>{{ byline }}</span></div>`,
 layoutCss:`
.starter[data-design="writer"] { max-width:64rem; }
.starter[data-design="writer"] .st-hero { grid-template-columns:1fr; gap:2rem; text-align:center; border-block:1px solid var(--border); padding-block:3rem; }
.starter[data-design="writer"] .st-hero h1,.starter[data-design="writer"] .st-hero .st-lead { margin-inline:auto; }
.starter[data-design="writer"] .st-actions { justify-content:center; }
.starter[data-design="writer"] .st-hero .st-cover { width:min(100%,24rem); margin:auto; aspect-ratio:16/9; }
.starter[data-design="writer"] .st-grid { grid-template-columns:1fr; gap:0; }
.starter[data-design="writer"] .st-card { border:0; border-bottom:1px solid var(--border); border-radius:0; padding:2rem 0; }
.starter[data-design="writer"] .st-card .st-cover { width:8rem; float:right; margin:0 0 1rem 1rem; }
.starter[data-design="writer"] .st-card h2 { font-size:2rem; }
.starter[data-design="writer"] .st-body { max-width:38rem; font-size:1.2rem; line-height:1.9; }
.starter[data-design="writer"] .st-end { text-align:center; }
.starter[data-design="writer"] .st-end .st-lead { margin-inline:auto; }
@media(max-width:520px) { .starter[data-design="writer"] .st-card .st-cover { width:6rem; } }
`,
 home:{eyebrow:"An independent publication",heading:"A place to think out loud.",intro:"Introduce the questions you return to, the things you notice, and why you write. Give readers a sense of the person behind the words.",imagePlaceholder:"Add a portrait or an illustration",browseLabel:"Read the essays",browseUrl:"/essays/",contactLabel:"Write to me",contactUrl:"",aboutTitle:"Behind the words",aboutText:"Share a little of your story and what you are working on now.",services:[{title:"Observations",description:"Small details that deserve a closer look."},{title:"Questions",description:"Ideas to sit with, without rushing to an answer."},{title:"Field notes",description:"What experience teaches along the way."}],demoNote:"Starter content. Replace the introduction and example essays before publishing."},
 samples:[{stem:"example-paying-attention",data:{title:"Example: on paying attention",summary:"An opening essay for your publication. Replace this with your own writing.",topic:"Observations",byline:"Your name"},body:"<h2>Start with something you noticed</h2><p>This is an example essay. Replace it with your own experience, argument and conclusion.</p>"},{stem:"example-open-question",data:{title:"Example: an open question",summary:"Some thoughts need space before they need answers.",topic:"Questions",byline:"Your name"},body:"<p>Use this space to develop a question in your own words.</p>"}]}),
 starter({id:"events",label:"Events",description:"A bold home for gatherings, with a browsable programme and practical event details.",collection:"events",singular:"Event",listingHeading:"The programme",base:"events",features:["Editable organizer introduction","Programme and event pages","Date, venue and admission details","External ticket links","Five brand styles"],notIncluded:["Ticket sales or payment processing","Booking management","Calendar synchronization"],
 fields:[field("dateDisplay","Date and time","string",{hint:"Include the timezone, for example 12 October 2026, 18:00–20:00 UTC."}),field("venue","Venue"),field("admission","Admission"),field("ticketLabel","Ticket link text"),field("ticketUrl","Ticket URL"),field("dateLabel","Date label","string",{default:"When"}),field("venueLabel","Venue label","string",{default:"Where"}),field("admissionLabel","Admission label","string",{default:"Admission"})],itemFields:["dateDisplay","venue","admission"],
 detailContent:`<p class="st-kicker">{{ dateDisplay }}</p><h1>{{ title }}</h1><p class="st-lead">{{ summary }}</p><dl class="st-facts"><div><dt>{{ dateLabel }}</dt><dd>{{ dateDisplay }}</dd></div><div><dt>{{ venueLabel }}</dt><dd>{{ venue }}</dd></div><div><dt>{{ admissionLabel }}</dt><dd>{{ admission }}</dd></div></dl>{{#if ticketUrl}}<div class="st-actions"><a class="st-button" href="{{ ticketUrl }}">{{ ticketLabel }} ↗</a></div>{{/if}}{{#if featuredImage}}<div class="st-cover"><img src="{{ featuredImage }}" alt="{{ imageAlt }}" /></div>{{/if}}`,cardContent:`<p class="st-kicker">{{ dateDisplay }}</p><div class="st-meta"><span>{{ venue }}</span><span>{{ admission }}</span></div>`,
 layoutCss:`
.starter[data-design="events"] .st-hero { grid-template-columns:1.5fr 1fr; padding:clamp(1rem,4vw,3rem); background:var(--surface); border-top:8px solid var(--accent); gap:2rem; }
.starter[data-design="events"] .st-hero h1 { font-size:clamp(2.7rem,7vw,6rem); letter-spacing:-.055em; }
.starter[data-design="events"] .st-hero .st-cover { aspect-ratio:1; border-radius:50%; border:2px solid var(--accent); }
.starter[data-design="events"] .st-card { border:0; border-top:3px solid var(--accent); border-radius:0; background:var(--surface); }
.starter[data-design="events"] .st-facts { background:var(--surface); padding:1.5rem; }
@media(max-width:800px) { .starter[data-design="events"] .st-hero { grid-template-columns:1fr; } .starter[data-design="events"] .st-hero .st-cover { max-width:20rem; width:100%; margin:auto; } }
`,
 home:{eyebrow:"Good company. New perspectives.",heading:"Make room for something happening.",intro:"Bring people together around a shared interest. Introduce your gatherings and let visitors know what to expect.",imagePlaceholder:"Add an image from your gathering",browseLabel:"See the programme",browseUrl:"/events/",contactLabel:"Get in touch",contactUrl:"",aboutTitle:"Come curious. Leave connected.",aboutText:"Tell people who organizes these events, who they are for, and how to take part.",services:[{title:"Meet",description:"Conversations with people who share your curiosity."},{title:"Learn",description:"New ideas and practical things to take home."},{title:"Take part",description:"A welcoming place to contribute your perspective."}],demoNote:"Starter content. Example events are fictional; add confirmed dates, venues and links before publishing."},
 samples:[{stem:"example-open-studio",data:{title:"Example: open studio",summary:"A fictional gathering to demonstrate the programme.",dateDisplay:"Date to be announced",venue:"Example studio",admission:"Details to be announced",dateLabel:"When",venueLabel:"Where",admissionLabel:"Admission"},body:"<h2>What to expect</h2><p>Replace this example with your event description, accessibility information and confirmed practical details.</p>"},{stem:"example-workshop",data:{title:"Example: a shared workshop",summary:"A second example, ready for a real event of your own.",dateDisplay:"Date to be announced",venue:"Example venue",admission:"Details to be announced",dateLabel:"When",venueLabel:"Where",admissionLabel:"Admission"},body:"<p>Add your workshop description and what participants should bring.</p>"}]})
);
export function starterSummary(starter) {
 return {id:starter.id,label:starter.label,description:starter.description,version:starter.version,features:starter.features,notIncluded:starter.notIncluded,looks:starter.looks.map(({id,label,description,brand})=>({id,label,description,colors:brand.colors})),collection:starter.contentType.name,base:starter.contentType.route.base};
}
