// First-party site starters: presentation + content model + sample content.
// Templates consume brand tokens, so the same functionality works with every look.
const field = (name, label, widget = "string", extra = {}) => ({ name, label, widget, required: false, ...extra });
const looks = [
  { id: "editorial", label: "Editorial", description: "Warm paper, confident type, terracotta details.", brand: { scheme: "light", radius: "2px", motion: "off", fonts: { heading: "jost", body: "jost" }, colors: { bg: "#f5f3eb", surface: "#e9e7db", ink: "#252621", muted: "#64675c", accent: "#b53b20", border: "#d9d9cd" } } },
  { id: "gallery", label: "Gallery", description: "Bright canvas, restrained green, room for images.", brand: { scheme: "light", radius: "8px", motion: "off", fonts: { heading: "inter", body: "inter" }, colors: { bg: "#ffffff", surface: "#f0f3f0", ink: "#172a24", muted: "#52655c", accent: "#28694d", border: "#d5dfd9" } } },
  { id: "nocturne", label: "Nocturne", description: "Dark surfaces, warm text and a soft lime accent.", brand: { scheme: "dark", radius: "4px", motion: "off", fonts: { heading: "space-grotesk", body: "inter" }, colors: { bg: "#20231e", surface: "#2c3028", ink: "#f4f3e8", muted: "#b7c0ad", accent: "#d3e5a9", border: "#4d5544" } } },
];
const css = `<style>
.starter { max-width:76rem; margin:auto; padding:clamp(2rem,5vw,5rem) 1.5rem; color:var(--ink); background:var(--paper); font-family:var(--font-prose); }
.starter a { color:var(--accent); text-underline-offset:.22em; }
.starter a:focus-visible { outline:3px solid var(--accent); outline-offset:4px; }
.starter .st-kicker { font:.7rem var(--font-mono); letter-spacing:.13em; text-transform:uppercase; color:var(--accent); }
.starter h1 { font-family:var(--font-heading); font-size:clamp(2.7rem,6vw,5.5rem); font-weight:500; letter-spacing:-.045em; line-height:1.04; margin:1.2rem 0; max-width:16ch; }
.starter .st-lead { font-size:1.2rem; line-height:1.75; color:var(--muted); max-width:40rem; white-space:pre-line; }
.starter .st-actions { display:flex; flex-wrap:wrap; gap:1rem; margin:2rem 0; }
.starter .st-button { display:inline-block; padding:.8rem 1.2rem; background:var(--ink); color:var(--paper); border-radius:var(--radius); text-decoration:none; }
.starter .st-hero { display:grid; grid-template-columns:1.25fr 1fr; gap:4rem; align-items:center; padding-bottom:3rem; }
.starter .st-cover { aspect-ratio:4/3; overflow:hidden; background:var(--surface); border:1px solid var(--border); border-radius:var(--radius); display:grid; place-items:center; position:relative; }
.starter .st-cover img { width:100%; height:100%; object-fit:cover; position:absolute; inset:0; }
.starter .st-cover > span { padding:1rem; font-family:var(--font-mono); font-size:.8rem; color:var(--muted); text-align:center; }
.starter .st-grid { display:grid; grid-template-columns:repeat(3,minmax(0,1fr)); gap:1.5rem; margin:2.5rem 0; }
.starter .st-card { border:1px solid var(--border); border-radius:var(--radius); padding:1.5rem; }
.starter .st-card h2,.starter .st-card h3 { font-family:var(--font-heading); font-size:1.5rem; line-height:1.2; font-weight:500; margin:1.2rem 0 .6rem; }
.starter .st-card p { line-height:1.7; color:var(--muted); }
.starter .st-meta { display:flex; flex-wrap:wrap; gap:.6rem 1.2rem; color:var(--muted); font-size:.9rem; }
.starter .st-status { display:inline-block; background:var(--surface); padding:.3rem .65rem; border-radius:var(--radius); margin:.75rem 0; font-size:.8rem; }
.starter .st-body { max-width:46rem; font-size:1.15rem; line-height:1.8; margin:3rem auto; }
.starter .st-body img { max-width:100%; height:auto; }
.starter .st-facts { display:grid; grid-template-columns:repeat(3,1fr); gap:1rem; padding:1.5rem 0; border-block:1px solid var(--border); }
.starter .st-facts dt { font-size:.75rem; color:var(--muted); } .starter .st-facts dd { font-size:1.2rem; margin:.4rem 0; }
.starter .st-gallery { display:grid; grid-template-columns:repeat(2,minmax(0,1fr)); gap:1rem; margin-top:2rem; }
.starter .st-gallery figure { margin:0; } .starter .st-gallery img { width:100%; aspect-ratio:4/3; object-fit:cover; border-radius:var(--radius); } .starter .st-gallery figcaption { font-size:.8rem; color:var(--muted); margin:.5rem 0; }
.starter .st-end { margin-top:4rem; padding-top:2rem; border-top:1px solid var(--border); }
.starter .st-demo { padding:.65rem 1rem; border:1px dashed var(--border); color:var(--muted); font-size:.8rem; margin-bottom:1rem; }
@media(max-width:800px) { .starter .st-hero { grid-template-columns:1fr; gap:1.5rem; } .starter .st-grid { grid-template-columns:repeat(2,minmax(0,1fr)); } }
@media(max-width:520px) { .starter .st-grid,.starter .st-gallery { grid-template-columns:1fr; } .starter .st-facts { grid-template-columns:repeat(2,1fr); } }
</style>`;
const homeFields = [field("eyebrow", "Introduction label", "string", {group:"Introduction"}), field("heading", "Headline", "string", {required:true,group:"Introduction"}), field("intro", "Introduction", "text", {group:"Introduction"}), field("featuredImage", "Cover image", "image", {group:"Introduction"}), field("imageAlt", "Image description", "string", {group:"Introduction"}), field("imagePlaceholder", "Image placeholder", "string", {group:"Introduction"}), field("browseLabel", "Browse button", "string", {group:"Links"}), field("browseUrl", "Browse URL", "string", {group:"Links"}), field("contactLabel", "Contact link text", "string", {group:"Contact"}), field("contactUrl", "Contact link", "string", {group:"Contact",hint:"Your mailto: email link or contact page URL. Leave blank to hide."}),field("aboutTitle", "About heading", "string", {group:"About"}),field("aboutText", "About text", "text", {group:"About"}),field("services", "Areas of work", "list", {group:"Areas of work",fields:[field("title","Title"),field("description","Description","text")]}),field("demoNote", "Starter note", "text", {group:"Getting ready",hint:"Replace the sample content, then clear this note before publishing."})];
const homeHtml = `${css}<section class="starter">{{#if demoNote}}<p class="st-demo">{{ demoNote }}</p>{{/if}}<div class="st-hero"><div><p class="st-kicker">{{ eyebrow }}</p><h1>{{ heading }}</h1><p class="st-lead">{{ intro }}</p><div class="st-actions"><a class="st-button" href="{{ browseUrl }}">{{ browseLabel }} ↗</a>{{#if contactUrl}}<a href="{{ contactUrl }}">{{ contactLabel }}</a>{{/if}}</div></div><div class="st-cover"><span>{{ imagePlaceholder }}</span>{{#if featuredImage}}<img src="{{ featuredImage }}" alt="{{ imageAlt }}" />{{/if}}</div></div><div class="st-grid">{{#each services}}<article class="st-card"><h2>{{ title }}</h2><p>{{ description }}</p></article>{{/each}}</div><section class="st-end"><h2>{{ aboutTitle }}</h2><p class="st-lead">{{ aboutText }}</p></section></section>`;
const galleryField = field("gallery", "Image gallery", "list", { fields: [field("image", "Image", "image"),field("alt", "Image description"),field("caption", "Caption")] });
const galleryHtml = `{{#if gallery}}<div class="st-gallery">{{#each gallery}}{{#if image}}<figure><img src="{{ image }}" alt="{{ alt }}" loading="lazy" />{{#if caption}}<figcaption>{{ caption }}</figcaption>{{/if}}</figure>{{/if}}{{/each}}</div>{{/if}}`;
function starter({id,label,description,collection,base,features,notIncluded,fields,itemFields,detailContent,cardContent,home,samples}) {
 const detail = `${id}-detail`, listing=`${id}-index`, landing=`${id}-home`;
 const allFields=[field("title","Title","string",{required:true}),field("summary","Summary","text"),field("featuredImage","Featured image","image"),field("imageAlt","Image description"),...fields,galleryField,field("contactLabel","Contact link text"),field("contactUrl","Contact link","string",{hint:"mailto: address or a contact-page URL. No form service is connected."}),field("demoNote","Example-content note","text"),field("draft","Draft","boolean",{default:true})];
 return { id,label,description,version:"1.0.0",features,notIncluded,looks,
  contentType:{name:collection,label:collection[0].toUpperCase()+collection.slice(1),labelSingular:collection==='projects'?'Project':'Property',folder:`content/${collection}`,localized:true,body:"rich",thumbnail:"featuredImage",fieldsFrom:detail,route:{base,template:detail,list:{template:listing,sortBy:"title",order:"asc",slots:{heading:collection==='projects'?'Selected work':'Property collection',intro:'Example content. Replace these entries with your own before publishing.',emptyText:'New entries will appear here when they are marked Ready.'}}}},
  home:{stem:id,preset:landing,title:label,slots:home},samples,
  templates:{
   [landing]:{position:"page",fields:{name:landing,label:`${label} introduction`,body:false,fields:homeFields},html:homeHtml},
   [detail]:{position:"detail",fields:{name:detail,label:`${label} detail`,body:true,fields:allFields},html:`${css}<article class="starter"><a href="{{ indexUrl }}">← Back to ${collection}</a>{{#if demoNote}}<p class="st-demo">{{ demoNote }}</p>{{/if}}${detailContent}<div class="st-body">{{{ body }}}</div>${galleryHtml}{{#if contactUrl}}<div class="st-end"><a class="st-button" href="{{ contactUrl }}">{{ contactLabel }} ↗</a></div>{{/if}}</article>`},
   [listing]:{position:"list",fields:{name:listing,label:`${label} listing`,body:false,listing:{of:collection,item:["title","summary","featuredImage","imageAlt",...itemFields]},fields:[field("heading","Heading","string",{required:true}),field("intro","Introduction","text"),field("emptyText","Empty state")]},html:`${css}<section class="starter"><h1>{{ heading }}</h1><p class="st-lead">{{ intro }}</p><div class="st-grid">{{#each entries}}<article class="st-card"><a href="{{ url }}"><div class="st-cover"><span>{{ title }}</span>{{#if featuredImage}}<img src="{{ featuredImage }}" alt="{{ imageAlt }}" loading="lazy" />{{/if}}</div><h2>{{ title }}</h2></a><p>{{ summary }}</p>${cardContent}</article>{{/each}}</div>{{#if isEmpty}}<p class="st-lead">{{ emptyText }}</p>{{/if}}</section>`},
  },
 };
}
export const STARTERS = [
 starter({id:"portfolio",label:"Portfolio",description:"An editorial home for independent creatives, studios and their work.",collection:"projects",base:"projects",features:["Editable introduction page","Project index and case studies","Project categories, client and year","Image galleries","Email or contact-page links","Three brand styles"],notIncluded:["File delivery or client accounts","Payments","Contact-form processing"],
 fields:[field("category","Discipline"),field("client","Client"),field("year","Year")],itemFields:["category","year"],
 detailContent:`<p class="st-kicker">{{ category }}</p><h1>{{ title }}</h1><p class="st-lead">{{ summary }}</p><div class="st-meta">{{#if client}}<span>{{ client }}</span>{{/if}}{{#if year}}<span>{{ year }}</span>{{/if}}</div>{{#if featuredImage}}<div class="st-cover"><img src="{{ featuredImage }}" alt="{{ imageAlt }}" /></div>{{/if}}`,cardContent:`<div class="st-meta"><span>{{ category }}</span><span>{{ year }}</span></div>`,
 home:{eyebrow:"Independent practice",heading:"Good work, thoughtfully made.",intro:"Introduce your practice, your point of view and the people you help. This space is yours to make specific.",imagePlaceholder:"Add a project image",browseLabel:"Explore the work",browseUrl:"/projects/",contactLabel:"Start a conversation",contactUrl:"",aboutTitle:"A practice with a point of view.",aboutText:"Replace this with a short introduction to your work and how you collaborate.",services:[{title:"Identity",description:"Describe the first area of your practice."},{title:"Digital",description:"Describe the second area of your practice."},{title:"Collaboration",description:"Explain how you work with clients and collaborators."}],demoNote:"Starter content. Add your words, images and contact details before publishing."},
 samples:[{stem:"example-identity",data:{title:"Example: a visual identity",summary:"Replace this example with the context and outcome of a real project.",category:"Brand identity",client:"Example client",year:"2026"},body:"<h2>The brief</h2><p>Describe the problem you helped solve.</p><h2>The work</h2><p>Tell the story behind your decisions and the result.</p>"},{stem:"example-digital",data:{title:"Example: a digital experience",summary:"A second case study, ready for your own story and images.",category:"Digital design",year:"2026"},body:"<p>Use this space for the story of your project.</p>"}]}),
 starter({id:"real-estate",label:"Real estate",description:"A considered property showcase with structured listings and useful detail pages.",collection:"properties",base:"properties",features:["Editable agency introduction","Property index and detail pages","Price, location and property facts","Availability status","Property galleries","Email or contact-page links","Three brand styles"],notIncluded:["MLS / IDX property feeds","Map or geocoding services","Booking and inquiry-form processing","Search and filter controls"],
 fields:[field("price","Price display","string",{hint:"Include the currency and any period, for example €1,500 / month."}),field("location","Location"),field("status","Availability","select",{options:["Available","Under offer","Sold","Let"]}),field("bedrooms","Bedrooms","number",{valueType:"int"}),field("bathrooms","Bathrooms","number"),field("area","Area, including units"),field("bedroomsLabel","Bedrooms label","string",{default:"Bedrooms"}),field("bathroomsLabel","Bathrooms label","string",{default:"Bathrooms"}),field("areaLabel","Area label","string",{default:"Area"})],itemFields:["price","location","status","bedrooms","bathrooms","area","bedroomsLabel","bathroomsLabel"],
 detailContent:`<p class="st-kicker">{{ location }}</p><h1>{{ title }}</h1><p class="st-lead">{{ summary }}</p><div class="st-meta"><strong>{{ price }}</strong>{{#if status}}<span class="st-status">{{ status }}</span>{{/if}}</div>{{#if featuredImage}}<div class="st-cover"><img src="{{ featuredImage }}" alt="{{ imageAlt }}" /></div>{{/if}}<dl class="st-facts"><div><dt>{{ bedroomsLabel }}</dt><dd>{{ bedrooms }}</dd></div><div><dt>{{ bathroomsLabel }}</dt><dd>{{ bathrooms }}</dd></div><div><dt>{{ areaLabel }}</dt><dd>{{ area }}</dd></div></dl>`,cardContent:`<p>{{ location }}</p><strong>{{ price }}</strong>{{#if status}}<span class="st-status">{{ status }}</span>{{/if}}<div class="st-meta"><span>{{ bedrooms }} {{ bedroomsLabel }}</span><span>{{ bathrooms }} {{ bathroomsLabel }}</span><span>{{ area }}</span></div>`,
 home:{eyebrow:"A local perspective",heading:"Find your next place in the world.",intro:"Introduce your agency and the places you know best. Give people a reason to trust your local knowledge.",imagePlaceholder:"Add a property or neighborhood image",browseLabel:"Explore properties",browseUrl:"/properties/",contactLabel:"Talk to us",contactUrl:"",aboutTitle:"Good advice starts with listening.",aboutText:"Explain how you help buyers, sellers or renters. Add your own qualifications and service area.",services:[{title:"Buy",description:"Describe how you help people find a home."},{title:"Sell",description:"Explain your approach to presenting a property."},{title:"Local knowledge",description:"Introduce the areas you work in."}],demoNote:"Starter content. Replace the example properties, text and contact details before publishing."},
 samples:[{stem:"example-courtyard-home",data:{title:"Example: courtyard home",summary:"Fictional property for demonstrating the layout. Replace with a real, authorized listing.",price:"Example price",location:"Example neighborhood",status:"Available",bedrooms:3,bathrooms:2,area:"Example area",bedroomsLabel:"Bedrooms",bathroomsLabel:"Bathrooms",areaLabel:"Area"},body:"<h2>About this property</h2><p>This is sample content, not a real listing. Add an accurate description, photographs and contact details for your own property.</p>"},{stem:"example-city-apartment",data:{title:"Example: city apartment",summary:"A fictional second listing to show the property collection.",price:"Example price",location:"Example district",status:"Under offer",bedrooms:2,bathrooms:1,area:"Example area",bedroomsLabel:"Bedrooms",bathroomsLabel:"Bathrooms",areaLabel:"Area"},body:"<p>Replace this sample with your own authorized property information.</p>"}]}),
];
export function starterSummary(starter) {
 return {id:starter.id,label:starter.label,description:starter.description,version:starter.version,features:starter.features,notIncluded:starter.notIncluded,looks:starter.looks.map(({id,label,description,brand})=>({id,label,description,colors:brand.colors})),collection:starter.contentType.name,base:starter.contentType.route.base};
}
