// ⚠️ GENERATED by scripts/gen-content-config.mjs from frontend/data/schema.json.
// Do not edit by hand — regenerated on every build. Change the model in the CMS
// content-type editor (or schema.json) instead.
//
// Localized collections store one subfolder per locale, so the glob loader yields
// id = "<locale>/<stem>" (e.g. "en/about"); routing parses that via
// frontend/lib/i18n.ts. Flat collections keep the bare stem. The glob loader is
// identical either way — the "**" pattern captures the locale subfolder — so this
// file does not distinguish them.
import { defineCollection } from "astro:content";
import { z } from "astro:schema";
import { glob } from "astro/loaders";

const posts = defineCollection({
  loader: glob({ pattern: "**/*.{md,mdx}", base: "./frontend/content/posts" }),
  schema: z.object({
    title: z.string(),
    seo: z.object({
      metaTitle: z.string().optional(),
      metaDescription: z.string().optional(),
      ogImage: z.string().optional(),
      canonical: z.string().optional(),
      ogType: z.enum(["website", "article"]).default("article"),
      noindex: z.boolean().default(false),
      author: z.string().optional(),
    }).optional(),
    pubDate: z.coerce.date(),
    updatedDate: z.preprocess(
      (v) => (v === "" || v === null ? undefined : v),
      z.coerce.date().optional(),
    ),
    draft: z.boolean().default(true),
    description: z.string().optional(),
    featuredImage: z.string().optional(),
    categories: z.array(z.string()).default([]),
    tags: z.array(z.string()).default([]),
    author: z.string().optional(),
    template: z.enum(["default", "full-width", "landing"]).default("default"),
  }),
});

const pages = defineCollection({
  loader: glob({ pattern: "**/*.{md,mdx}", base: "./frontend/content/pages" }),
  schema: z.object({
    title: z.string(),
    draft: z.boolean().default(true),
    seo: z.object({
      metaTitle: z.string().optional(),
      metaDescription: z.string().optional(),
      ogImage: z.string().optional(),
      canonical: z.string().optional(),
      ogType: z.enum(["website", "article"]).default("website"),
      noindex: z.boolean().default(false),
    }).optional(),
    description: z.string().optional(),
    featuredImage: z.string().optional(),
    template: z.enum(["default", "full-width", "landing"]).default("default"),
    preset: z.string().optional(),
    slots: z.record(z.string(), z.any()).optional(),
    blocks: z.array(
      z.discriminatedUnion("type", [
        z.object({
          type: z.literal("hero"),
          heading: z.string(),
          subheading: z.string().optional(),
          image: z.string().optional(),
          ctaText: z.string().optional(),
          ctaUrl: z.string().optional(),
        }),
        z.object({
          type: z.literal("text"),
          body: z.string(),
        }),
        z.object({
          type: z.literal("image"),
          image: z.string(),
          alt: z.string().optional(),
          caption: z.string().optional(),
        }),
        z.object({
          type: z.literal("gallery"),
          images: z.array(z.object({
            image: z.string(),
            alt: z.string().optional(),
          })).default([]),
        }),
        z.object({
          type: z.literal("cta"),
          heading: z.string().optional(),
          text: z.string().optional(),
          buttonText: z.string(),
          buttonUrl: z.string(),
        }),
      ]),
    ).default([]),
  }),
});

const categories = defineCollection({
  loader: glob({ pattern: "**/*.{md,mdx}", base: "./frontend/content/categories" }),
  schema: z.object({
    title: z.string(),
    description: z.string().optional(),
    parent: z.string().optional(),
  }),
});

const tags = defineCollection({
  loader: glob({ pattern: "**/*.{md,mdx}", base: "./frontend/content/tags" }),
  schema: z.object({
    title: z.string(),
    description: z.string().optional(),
  }),
});

const authors = defineCollection({
  loader: glob({ pattern: "**/*.{md,mdx}", base: "./frontend/content/authors" }),
  schema: z.object({
    title: z.string(),
    bio: z.string().optional(),
    avatar: z.string().optional(),
  }),
});

const listings = defineCollection({
  loader: glob({ pattern: "**/*.{md,mdx}", base: "./frontend/content/listings" }),
  schema: z.object({
    title: z.string(),
    draft: z.boolean().default(true),
    seo: z.object({
      metaTitle: z.string().optional(),
      metaDescription: z.string().optional(),
      ogImage: z.string().optional(),
      canonical: z.string().optional(),
      ogType: z.enum(["website", "article"]).default("article"),
      noindex: z.boolean().default(false),
    }).optional(),
    pubDate: z.preprocess(
      (v) => (v === "" || v === null ? undefined : v),
      z.coerce.date().optional(),
    ),
    featuredImage: z.string().optional(),
    gallery: z.array(z.object({
      image: z.string(),
      alt: z.string().optional(),
    })).default([]),
    listingType: z.enum(["sale", "rent", "sale_and_rent"]).default("sale"),
    listingStatus: z.enum(["active", "under_offer", "sold", "rented"]).default("active"),
    priceSale: z.number().optional(),
    priceRent: z.number().optional(),
    bedrooms: z.number().optional(),
    bathrooms: z.number().optional(),
    areaM2: z.number().optional(),
    lotM2: z.number().optional(),
    latitude: z.number().optional(),
    longitude: z.number().optional(),
    region: z.string().optional(),
    agent: z.string().optional(),
    features: z.array(z.string()).default([]),
    flowTags: z.array(z.string()).default([]),
    template: z.enum(["default", "full-width", "landing"]).default("default"),
  }),
});

const regions = defineCollection({
  loader: glob({ pattern: "**/*.{md,mdx}", base: "./frontend/content/regions" }),
  schema: z.object({
    title: z.string(),
    description: z.string().optional(),
  }),
});

const agents = defineCollection({
  loader: glob({ pattern: "**/*.{md,mdx}", base: "./frontend/content/agents" }),
  schema: z.object({
    title: z.string(),
    photo: z.string().optional(),
    role: z.string().optional(),
    phone: z.string().optional(),
    whatsapp: z.string().optional(),
    email: z.string().optional(),
    telegramChatId: z.string().optional(),
  }),
});

export const collections = { posts, pages, categories, tags, authors, listings, regions, agents };
