// ⚠️ GENERATED by scripts/gen-content-config.mjs from data/schema.json.
// Do not edit by hand — regenerated on every build. Change the model in the CMS
// content-type editor (or schema.json) instead.
//
// Localized collections store one subfolder per locale, so the glob loader yields
// id = "<locale>/<stem>" (e.g. "en/about"); routing parses that via
// frontend/lib/i18n.ts. Flat collections keep the bare stem. The glob loader is
// identical either way — the "**" pattern captures the locale subfolder — so this
// file does not distinguish them.
import { defineCollection } from "astro:content";
import { z } from "astro:schema";
import { glob } from "astro/loaders";

const posts = defineCollection({
  loader: glob({ pattern: "**/*.{md,mdx}", base: "./content/posts" }),
  schema: z.object({
    "title": z.string(),
    "seo": z.object({
      "metaTitle": z.string().optional(),
      "metaDescription": z.string().optional(),
      "ogImage": z.string().optional(),
      "canonical": z.string().optional(),
      "ogType": z.enum(["website", "article"]).default("article"),
      "noindex": z.boolean().default(false),
      "author": z.string().optional(),
    }).optional(),
    "pubDate": z.coerce.date(),
    "updatedDate": z.preprocess(
      (v) => (v === "" || v === null ? undefined : v),
      z.coerce.date().optional(),
    ),
    "draft": z.boolean().default(true),
    "description": z.string().optional(),
    "featuredImage": z.string().optional(),
    "categories": z.array(z.string()).default([]),
    "tags": z.array(z.string()).default([]),
    "author": z.string().optional(),
    "template": z.enum(["default", "full-width", "landing"]).default("default"),
  }),
});

const pages = defineCollection({
  loader: glob({ pattern: "**/*.{md,mdx}", base: "./content/pages" }),
  schema: z.object({
    "title": z.string(),
    "draft": z.boolean().default(true),
    "seo": z.object({
      "metaTitle": z.string().optional(),
      "metaDescription": z.string().optional(),
      "ogImage": z.string().optional(),
      "canonical": z.string().optional(),
      "ogType": z.enum(["website", "article"]).default("website"),
      "noindex": z.boolean().default(false),
    }).optional(),
    "description": z.string().optional(),
    "featuredImage": z.string().optional(),
    "template": z.enum(["default", "full-width", "landing"]).default("default"),
    "preset": z.string().optional(),
    "slots": z.record(z.string(), z.any()).optional(),
  }),
});

const categories = defineCollection({
  loader: glob({ pattern: "**/*.{md,mdx}", base: "./content/categories" }),
  schema: z.object({
    "title": z.string(),
    "description": z.string().optional(),
    "parent": z.string().optional(),
  }),
});

const tags = defineCollection({
  loader: glob({ pattern: "**/*.{md,mdx}", base: "./content/tags" }),
  schema: z.object({
    "title": z.string(),
    "description": z.string().optional(),
  }),
});

const authors = defineCollection({
  loader: glob({ pattern: "**/*.{md,mdx}", base: "./content/authors" }),
  schema: z.object({
    "title": z.string(),
    "bio": z.string().optional(),
    "avatar": z.string().optional(),
  }),
});

export const collections = { posts, pages, categories, tags, authors };
