import { defineConfig } from "vite";
import vue from "@vitejs/plugin-vue";
import tailwindcss from "@tailwindcss/vite";

// Lanza CMS — the admin app. Builds to ../public/admin/ (replacing Sveltia),
// served as a static SPA by Astro/Pages at /admin/. The output is gitignored and
// regenerated by the deploy build (see the root `build` script).
export default defineConfig({
  base: "/admin/",
  plugins: [vue(), tailwindcss()],
  build: {
    outDir: "../public/admin",
    emptyOutDir: true,
  },
});
