import { defineConfig } from "vite";
import vue from "@vitejs/plugin-vue";
import tailwindcss from "@tailwindcss/vite";

// Lanza CMS — the admin app. Builds to ../public/admin/ (replacing Sveltia),
// served as a static SPA by Astro/Pages at /admin/. The output is gitignored and
// regenerated by the deploy build (see the root `build` script).
export default defineConfig({
  base: "/admin/",
  plugins: [vue(), tailwindcss()],
  // Dev server serves the SPA under the `/admin/` base. `open` lands the browser
  // on the working URL (the bare root 404s because of the base). Vite picks the
  // next free port automatically if 5173 is taken (strictPort defaults false).
  server: {
    open: "/admin/",
  },
  build: {
    outDir: "../public/admin",
    emptyOutDir: true,
  },
});
