import { defineConfig, loadEnv, type Plugin } from "vite";
import vue from "@vitejs/plugin-vue";
import tailwindcss from "@tailwindcss/vite";
// Shared proxy policy — same module the prod Pages Function uses, so the
// allowlist and CSRF check can't drift between dev and prod.
import { crossOriginBlocked, isAllowed } from "../functions/_lib/gh-proxy";

// Dev mirror of the production Pages Function (functions/admin/api/gh/[[path]].ts).
// Intercepts /admin/api/gh/* in the Vite dev server and proxies to GitHub with
// the token injected server-side, so the SPA never holds a token in dev either.
// The token comes from admin/.env (GITHUB_TOKEN, NON-VITE-prefixed → never
// bundled, never reaches the client). Same client code runs in dev and prod.
function githubProxyDev(token: string | undefined): Plugin {
  return {
    name: "lanza-github-proxy-dev",
    configureServer(server) {
      // connect strips the mount prefix, so `req.url` is the path *after*
      // /admin/api/gh — exactly what we append to api.github.com.
      server.middlewares.use("/admin/api/gh", async (req, res) => {
        // Cast to minimal shapes — @types/node isn't installed, so the connect
        // IncomingMessage/ServerResponse types don't expose these members here.
        const r = req as unknown as {
          url?: string;
          method?: string;
          headers: Record<string, string | undefined>;
        };
        const w = res as unknown as {
          statusCode: number;
          setHeader(name: string, value: string): void;
          end(chunk?: string): void;
        };

        const reject = (status: number, message: string) => {
          w.statusCode = status;
          w.setHeader("content-type", "application/json");
          w.end(JSON.stringify({ message }));
        };

        try {
          const method = r.method ?? "GET";
          const subPath = r.url ?? "";

          // Same allowlist + CSRF check as prod (functions/_lib/gh-proxy.ts).
          if (!isAllowed(method, subPath)) {
            reject(
              403,
              `Blocked by proxy allowlist: ${method} ${subPath} is not a permitted GitHub endpoint.`,
            );
            return;
          }
          if (crossOriginBlocked(method, r.headers["origin"] ?? null, r.headers["host"] ?? null)) {
            reject(403, "Cross-origin write rejected.");
            return;
          }

          if (!token) {
            w.statusCode = 500;
            w.setHeader("content-type", "application/json");
            w.end(
              JSON.stringify({
                message:
                  "Dev GitHub proxy: GITHUB_TOKEN is missing from admin/.env (copy .sample.env).",
              }),
            );
            return;
          }

          const target = `https://api.github.com${r.url ?? ""}`;

          let body = "";
          if (r.method !== "GET" && r.method !== "HEAD") {
            for await (const chunk of req as AsyncIterable<unknown>)
              body += String(chunk);
          }

          const upstream = await fetch(target, {
            method: r.method,
            headers: {
              Authorization: `Bearer ${token}`,
              Accept: r.headers["accept"] ?? "application/vnd.github+json",
              "X-GitHub-Api-Version": "2022-11-28",
              "User-Agent": "lanza-cms-dev",
              ...(r.headers["content-type"]
                ? { "Content-Type": r.headers["content-type"] }
                : {}),
            },
            body: body || undefined,
          });

          w.statusCode = upstream.status;
          const ct = upstream.headers.get("content-type");
          if (ct) w.setHeader("content-type", ct);
          w.end(await upstream.text());
        } catch (e) {
          w.statusCode = 502;
          w.setHeader("content-type", "application/json");
          w.end(
            JSON.stringify({
              message: `Dev GitHub proxy error: ${(e as Error).message}`,
            }),
          );
        }
      });
    },
  };
}

// Lanza CMS — the admin app. Builds to ../public/admin/ (replacing Sveltia),
// served as a static SPA by Astro/Pages at /admin/. The output is gitignored and
// regenerated by the deploy build (see the root `build` script).
export default defineConfig(({ mode }) => {
  // Prefix "" loads ALL vars (incl. non-VITE GITHUB_TOKEN) for config-time use
  // only — loadEnv does not expose them to the client bundle.
  const env = loadEnv(mode, ".", "");

  return {
    base: "/admin/",
    plugins: [vue(), tailwindcss(), githubProxyDev(env.GITHUB_TOKEN)],
    // Dev server serves the SPA under the `/admin/` base. `open` lands the browser
    // on the working URL (the bare root 404s because of the base). Vite picks the
    // next free port automatically if 5173 is taken (strictPort defaults false).
    server: {
      open: "/admin/",
    },
    build: {
      outDir: "../public/admin",
      emptyOutDir: true,
    },
  };
});
