// Filesystem-side enforcement: content must belong to the schema and page slots
// must belong to the selected template. The renderer cannot detect orphan files.
import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import yaml from 'js-yaml';

export function checkContent(root) {
  const problems = [];
  const error = (where, code, message) => problems.push({ level: 'error', where, code, message });
  const schema = JSON.parse(readFileSync(join(root, 'data/schema.json'), 'utf8'));
  const folders = schema.filter(c => c.kind === 'folder');
  function walk(dir) {
    if (!existsSync(join(root, dir))) return [];
    return readdirSync(join(root, dir), { withFileTypes: true }).flatMap(e =>
      e.isDirectory() ? walk(`${dir}/${e.name}`) : [`${dir}/${e.name}`]);
  }
  // Editorial routes must come from CMS entries. These are the platform's
  // infrastructure route families; custom collection routes are regenerated.
  const platformRoutes = new Set([
    'index.astro', '[...slug].astro', '404.astro',
    'posts/[...slug].astro', 'category/[slug].astro', 'tag/[slug].astro', 'author/[slug].astro',
    '[locale]/index.astro', '[locale]/[...slug].astro',
    '[locale]/posts/[...slug].astro', '[locale]/category/[slug].astro',
    '[locale]/tag/[slug].astro', '[locale]/author/[slug].astro',
    'style-preview/[...variant].astro', 'llms.txt.ts', 'site-system.json.ts',
  ]);
  for (const file of walk('frontend/pages')) {
    if (!/\.(astro|[cm]?[jt]s)$/.test(file)) continue;
    const route = file.slice('frontend/pages/'.length);
    if (platformRoutes.has(route)) continue;
    const source = readFileSync(join(root, file), 'utf8');
    if (source.includes('GENERATED by scripts/gen-routes.mjs from data/schema.json')) continue;
    error(file, 'route-outside-schema', 'Public content routes must use a CMS page or collection.route, not a handwritten route.');
  }
  const files = new Set([...walk('content'), ...folders.flatMap(c => walk(c.folder))]);
  function slots(value, fields, where) {
    if (!value || typeof value !== 'object' || Array.isArray(value)) {
      error(where, 'invalid-slots', 'Template content must be an object.'); return;
    }
    for (const [name, entry] of Object.entries(value)) {
      const field = fields.find(f => f.name === name);
      if (!field) { error(`${where}.${name}`, 'undeclared-content-field', 'No template field declares this value; the CMS cannot edit it.'); continue; }
      if (entry == null) continue;
      if (field.widget === 'object') slots(entry, field.fields ?? [], `${where}.${name}`);
      if (field.widget === 'list' && field.fields) {
        if (!Array.isArray(entry)) error(`${where}.${name}`, 'invalid-slots', 'List content must be an array.');
        else entry.forEach((item, i) => slots(item, field.fields, `${where}.${name}.${i}`));
      }
    }
  }
  for (const file of files) {
    if (!/\.md$/.test(file)) continue;
    if (!folders.some(c => file.startsWith(`${c.folder}/`))) {
      error(file, 'content-outside-schema', 'Declare this content folder in data/schema.json.'); continue;
    }
    let data;
    try { data = yaml.load(readFileSync(join(root, file), 'utf8').match(/^---\r?\n([\s\S]*?)\r?\n---(?:\r?\n|$)/)?.[1] ?? '') ?? {}; }
    catch (e) { error(file, 'invalid-frontmatter', e.message); continue; }
    const owner = folders.find(c => file.startsWith(`${c.folder}/`));
    if (owner?.name === 'pages' && Array.isArray(data.blocks) && data.blocks.length
        && !owner.fields?.some(field => field.name === 'blocks')) {
      error(file, 'legacy-blocks-without-schema', 'Migrate existing page blocks to a preset and slots before removing their schema field; otherwise the build would discard their content.');
    }
    if (!data.preset) continue;
    if (typeof data.preset !== 'string' || !/^[a-zA-Z0-9_-]+$/.test(data.preset)) {
      error(file, 'invalid-preset', 'Preset must name a template folder.'); continue;
    }
    const path = join(root, 'templates', data.preset);
    if (!existsSync(join(path, 'fields.json')) || !existsSync(join(path, 'template.html'))) {
      error(file, 'content-template-missing', `Template ${data.preset} needs fields.json and template.html.`); continue;
    }
    try { slots(data.slots ?? {}, JSON.parse(readFileSync(join(path, 'fields.json'), 'utf8')).fields ?? [], `${file}:slots`); }
    catch (e) { error(file, 'invalid-template-fields', e.message); }
  }
  return problems;
}
